### ISSUE TITLE
Lako je prevariti igru

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG086-geometry-race#2]
Pokušajte da napravite da nije ovoliko jednostavno prevariti igru. Elem, posto se blokovi stvaraju samo 'ispred' korisnika, ako se drzi taster 'd' i ne pusta, igrac nece nikad izgubiti.

**Comment by lukaking032** [comment]
Napravio sam tako da ako neka prepreka predje granicu levo ili desno, da se translira na suprotnu stranu, tako da korisnik ima iluziju da se prepreke loop-uju tako da nije vise moguce varati u igri :)
